baseURL = "https://blog.aidea775.com"
languageCode = "en-us"
DefaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
title = "AIDEA775's Blog"
paginate = 5

[author]
  name = "Silva Alejandro Ismael"

[params]
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = true


[languages]
  [languages.en]
    title = "AIDEA775's Blog"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      text = "AIDEA775"
      link = "/en"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/en/about"

  [languages.es]
    title = "El blog de AIDEA775"
    menuMore = "Más"
    readMore = "Leer más"
    readOtherPosts = "Leer otras publicaciones"

    [languages.es.params.logo]
      text = "AIDEA775 en español"
      link = "/es"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "about"
        name = "Sobre mí"
        url = "/es/about"
      [[languages.es.menu.main]]
        identifier = "notes"
        name = "Notas"
        url = "/es/notes"