# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Terminal8"
license = "CC"
licenselink = "https://creativecommons.org/licenses/by/4.0/"
description = "Terminal8 is a simple and truly colorful theme based on eight colors"
homepage = ""
tags = ["blog", "syntax highlighting"]
features = ["blog", "syntax highlighting"]
min_version = 1

[author]
  name = "Silva Alejandro Ismael"
  homepage = "https://github.com/AIDEA775"
